### PR TITLE
GH-59: Update to use better-maintained fork of jsonlint. (resolves #59)

### LINKED ISSUE #59: Move to prantl's jsonlint
@zaach ' s original jsonlint at https://github.com/zaach/jsonlint has been unmaintained for 5 years (see https://github.com/zaach/jsonlint/issues/140 ) and has been reporting critical security vulnerabilities in its dependencies for quite some while. This may alarm users of fluid-lint-all who are new to the ecosystem.

@prantlf has been maintaining a much improved fork of the project for the last 4 years at https://github.com/prantlf/jsonlint which looks like it reports errors more readably as well as handling JSON5 files. A good "rainy day" task could be to investigate moving over to it

### PR DESCRIPTION
**Pull request by duhrer**
See #59 for details.

### CODE REVIEW

**Comment by duhrer** [comment]
@amb26, the conversion was thankfully pretty easy, just removing my old monkey patches and changing the package name and a few variable names.

I also nudged other dependencies except for the two problematic ones, `stylelint` and `eslint-plugin-markdown`.  The former we won't upgrade until the community's rules are upgraded.    The latter would require a refactor.

**Comment by duhrer** [comment]
I also cut a dev release (`1.2.7-dev.20230303T094902Z.9877d02.GH-59`) for you to test with.

**Comment by amb26** [comment]
Thanks, works brilliantly!

**Comment by duhrer** [comment]
Thanks for the quick review.  I created the full release of `1.2.7` just now.

**Pull request merged**
