### PR TITLE
FLUID-6598 Test with Node.js 14 and 15

### PR DESCRIPTION
**Pull request by gtirloni**
Related: https://github.com/fluid-project/stylelint-config-fluid/pull/4

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
I'd like to chat through this one with you and @greatislander, I see the npm@7 issues in this branch but not in main.  When were the issues introduced, and where are they documented?

**Comment by greatislander** [comment]
@the-t-in-rtf I believe the history of this is:

1. @gtirloni updated some tests to drop Node 12 support and add Node 15 support, and ran into errors with dependency resolution for some of `stylelint-config-fluid`'s dependencies.
2. He was able to get them to install in Node 15 by using npm@6 instead of npm@7 (related to changes in [peer dependencies](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies) in npm@7. @jobara [noted in Matrix](https://matrix.to/#/!mDigWuPWilYGiEcOCA:matrix.org/$NcSna376pg7CrI_9LZ3W12nfq34SK9l34AoWy_Hmic4?via=matrix.org) that the same effect could be achieved in npm@7 by using the `--legacy-peer-deps` flag with `npm install`.
3. Since @gtirloni's initial PR, the upstream dependencies that were causing the problem have been updated and I can't reproduce the issue anymore with the latest versions of `stylelint-config-fluid`'s dependencies installed.

**Comment by the-t-in-rtf** [comment]
Thanks for the explanation, @greatislander.  If I update my copy of Gio's branch with the 0.20 release (and with the dev release of 0.3).  I still see dependency resolution issues in both with npm@7.  This might be one of those things where it doesn't show up in the package itself, but does in downstream projects.  Here's the error I see:

```
npm ERR! 
npm ERR! Found: stylelint@13.12.0
npm ERR! node_modules/stylelint-config-fluid/node_modules/stylelint
npm ERR!   stylelint@"13.12.0" from stylelint-config-fluid@0.2.0
npm ERR!   node_modules/stylelint-config-fluid
npm ERR!     stylelint-config-fluid@"0.2.0" from the root project
npm ERR!   peer stylelint@"^13.12.0" from stylelint-config-standard@21.0.0
npm ERR!   node_modules/stylelint-config-fluid/node_modules/stylelint-config-standard
npm ERR!     stylelint-config-standard@"21.0.0" from stylelint-config-fluid@0.2.0
npm ERR!     node_modules/stylelint-config-fluid
npm ERR!       stylelint-config-fluid@"0.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer stylelint@"^8.3.0 || ^9.0.0 || ^10.0.0" from stylelint-config-recommended@2.2.0
npm ERR! node_modules/stylelint-config-fluid/node_modules/stylelint-config-standard-scss/node_modules/stylelint-config-recommended
npm ERR!   stylelint-config-recommended@"^2.2.0" from stylelint-config-standard@18.3.0
npm ERR!   node_modules/stylelint-config-fluid/node_modules/stylelint-config-standard-scss/node_modules/stylelint-config-standard
npm ERR!     stylelint-config-standard@"~18.3.0" from stylelint-config-standard-scss@1.1.0
npm ERR!     node_modules/stylelint-config-fluid/node_modules/stylelint-config-standard-scss
npm ERR!       stylelint-config-standard-scss@"1.1.0" from stylelint-config-fluid@0.2.0
```

There are a few dependencies that are far out of date, I will prepare a pull against stylelint-config-fluid to update those, hopefully that will help.

@gtirloni, if you're willing, I'd like to ask you to back out the npm@6 workaround in this pull, and we'll test upstream changes to stylelint-config-fluid to see if we can find a proper fix.

**Comment by the-t-in-rtf** [comment]
Hmm, seems like you're already as up to date as you can be, and that we'd need a new release of one of the intermediate packages.  Never mind my comment about reverting, @gtirloni.   I will file a new ticket about fixing npm@7 support and will merge this change shortly.

**Pull request merged**
