### PR TITLE
Add ability to scan only staged files (resolves #62).

### LINKED ISSUE #62: Add the ability to lint only staged files
Currently, `fluid-lint-all` runs all checks against all the files it can find.  As mentioned by @greatislander in the Fluid group chats, this is slower than only linting files that have changed.

In thinking it through, I think we can fairly easily at a flag/configuration option to only lint uncommitted changes.

There is a [node wrapper for `git` commands](https://github.com/christkv/node-git/), but this seems excessive.

I was thinking of simply using `exec` and parsing the output, as we do elsewhere in this package.

`git` provides a machine-parseable format with its `-z` option:

```
> git status -z  
 M .eslintrc-fluid.json D fluid-config.js M package.json?? foobar%   
```

Each file entry is terminated with a NUL character (ASCII 0) and is separated from its status by a space operator.  Since we are filtering only to the changes, we don't need to worry about deleted content (`D` modifier).  Added (`A`), changed (`M`), and untracked files (`??`) should be included in the list of relative paths that have been changed.

Renamed files are slightly more complex.  In theory, we could just look for the `RM` modifier (renamed and modified), but this would be a problem in cases where the extension (and thus linting rules) change.  IMO we should include renamed (but otherwise unchanged) files (`R` modifier) in the scan.  The format for renamed files  also is slightly more complex, with three fields (modifier, old path, new path).  For both `R` and `RM`, we would simply add the new path to the list of changes.

Once we have the list of relative paths to include, we prepend the repository root to the path so that we can directly compare full paths.  We then derive the full list of potential files from command-line parameters and configuration files, as we usually do.  Right before scanning, we filter the files to those that have changed.  This allows authors to keep control over which files are checked where.

If there are no files to scan as a result of filtering for changes, there should be a clear message displayed for the relevant check.

### PR DESCRIPTION
**Pull request by duhrer**
See #62 for background.

### CODE REVIEW

**Comment by duhrer** [comment]
The test failure is a coverage failure, which completely makes sense, as I need to add tests.

**Comment by duhrer** [comment]
If anyone wants to try it, I cut a dev release, `fluid-lint-all@1.2.10-dev.20231103T135559Z.3b3787c.GH-62`.  The new flag is `--changedOnly`.

**Comment by duhrer** [comment]
I found a handful of goofs with the new tests, this should be ready to review now.

**Comment by duhrer** [comment]
@amb26, I have updated to avoid using `mv` directly in the tests, this should hopefully work on Windows as well.

**Comment by amb26** [comment]
I'm currently unable to test this on my machine because of the following issue running the tests - 

> fluid-lint-all@1.2.11 test E:\Source\gits\fluid-lint-all
> npx nyc@15.1.0 node tests/all-tests.js

npm ERR! cb.apply is not a function

I get this with main as well so the issue isn't related to this pull - I've attached the logs
[2024-04-09T14_49_52_581Z-debug.txt](https://github.com/fluid-project/fluid-lint-all/files/14920279/2024-04-09T14_49_52_581Z-debug.txt)
 but will try again when I get back to my main machine.

node version 16.6.2 npm 6.14.11 on Windows

**Review by greatislander — APPROVED** [review]

**Pull request merged**
